# Generated by Django 3.1.2 on 2020-11-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pin', models.Field(max_length=5)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
