# Generated by Django 3.1.2 on 2020-11-22 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0002_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 20, 35, 8, 418063), verbose_name='date published'),
        ),
    ]
