# Generated by Django 3.1.2 on 2020-11-22 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0004_auto_20201122_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 20, 38, 52, 150401), verbose_name='date published'),
        ),
    ]
