# Generated by Django 3.1.2 on 2020-11-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0007_auto_20201122_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
