# Generated by Django 3.1.2 on 2020-11-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0008_auto_20201122_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
