# Generated by Django 3.1.2 on 2020-12-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0009_auto_20201122_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
