# Generated by Django 3.1.2 on 2020-12-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0013_auto_20201207_0109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
