# Generated by Django 3.1.2 on 2020-12-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0017_auto_20201207_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='rapunzel.png', upload_to=''),
        ),
    ]
