# Generated by Django 3.1.2 on 2020-12-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0020_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pic',
            field=models.ImageField(blank=True, default='rapunzel.png', null=True, upload_to='images'),
        ),
    ]
