# Generated by Django 3.1.2 on 2020-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0023_auto_20201207_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age',
            name='user',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Age',
        ),
    ]
