# Generated by Django 3.1.2 on 2021-01-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0037_auto_20210118_2336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
