# Generated by Django 3.1.2 on 2021-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0039_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_user.png', upload_to=''),
        ),
    ]
