# Generated by Django 3.1.2 on 2021-01-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0040_auto_20210119_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_user.png', upload_to=''),
        ),
    ]
