# Generated by Django 3.1.2 on 2021-01-20 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riple', '0044_auto_20210120_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='Userfriend', to=settings.AUTH_USER_MODEL),
        ),
    ]
