# Generated by Django 3.1.2 on 2021-01-21 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riple', '0046_auto_20210121_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
