# Generated by Django 3.1.2 on 2021-01-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0052_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
