# Generated by Django 3.1.2 on 2021-01-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0053_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
