# Generated by Django 3.1.2 on 2021-01-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0055_auto_20210130_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='default_user.png', upload_to=''),
        ),
    ]
