# Generated by Django 3.1.2 on 2021-01-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0057_auto_20210130_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pic',
            new_name='post_pic',
        ),
    ]
