# Generated by Django 3.1.2 on 2021-01-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0060_auto_20210130_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='default_user.png', upload_to=''),
        ),
    ]
