# Generated by Django 3.1.2 on 2021-01-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0062_auto_20210131_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
