# Generated by Django 3.1.2 on 2021-01-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0063_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
