# Generated by Django 3.1.2 on 2021-02-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0065_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
