# Generated by Django 3.1.2 on 2021-02-06 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riple', '0067_feedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
