# Generated by Django 3.1.2 on 2021-02-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0070_profile_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
