# Generated by Django 3.1.2 on 2021-02-08 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riple', '0073_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='users',
            field=models.ManyToManyField(related_name='followers_of_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
