# Generated by Django 3.1.2 on 2021-02-08 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riple', '0074_auto_20210208_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
