# Generated by Django 3.1.2 on 2021-02-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0076_auto_20210208_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Comment'), (3, 'Follow'), (4, 'Request'), (5, 'Aceepted')]),
        ),
    ]
