# Generated by Django 3.1.2 on 2021-03-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0077_auto_20210208_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
