# Generated by Django 3.1.2 on 2021-03-06 12:38

from django.db import migrations, models
import riple.validators


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0081_auto_20210306_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[riple.validators.validate_file_extension]),
        ),
    ]
