# Generated by Django 3.1.2 on 2021-03-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0083_post_is_a_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_a_video',
            new_name='isvideo',
        ),
    ]
