# Generated by Django 3.1.2 on 2021-03-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0084_auto_20210306_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='isvideo',
            new_name='is_a_video',
        ),
    ]
