# Generated by Django 3.1.2 on 2021-03-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0085_auto_20210306_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
    ]
