# Generated by Django 3.1.2 on 2021-03-06 13:04

from django.db import migrations, models
import riple.validators


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0086_auto_20210306_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[riple.validators.validate_file_extension]),
        ),
    ]
