# Generated by Django 3.1.2 on 2021-03-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0087_post_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_a_video',
            new_name='isavideo',
        ),
    ]
