# Generated by Django 3.1.2 on 2021-03-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0089_auto_20210308_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='files/defaultdp.jpg', upload_to=''),
        ),
    ]
