# Generated by Django 3.1.2 on 2021-03-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riple', '0091_auto_20210312_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
